/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package form;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;


/**
 *
 * @author Ahmad Noval
 */
public class LaporanFrom extends javax.swing.JFrame {

    /**
     * Creates new form LaporanFrom
     */
    public LaporanFrom() {
        initComponents();
         setLocationRelativeTo(null);

    cmbLaporan.removeAllItems();

    cmbLaporan.addItem("Data Barang");
    cmbLaporan.addItem("Barang Masuk");
    cmbLaporan.addItem("Barang Keluar");
    cmbLaporan.addItem("Stock Opname");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbLaporan = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLaporan = new javax.swing.JTable();
        btnTampil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("LAPORAN");

        jLabel2.setText("Jenis Laporan");

        cmbLaporan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Data Barang Barang Masuk Barang Keluar Stock Opname" }));
        cmbLaporan.setSelectedIndex(-1);

        tblLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLaporan);

        btnTampil.setText("TAMPILKAN");
        btnTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(cmbLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(btnTampil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTampil)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model =
    new DefaultTableModel();
         try{

        Connection conn =
        koneksi.getConnection();

        String pilihan =
        cmbLaporan.getSelectedItem().toString();

        String sql = "";

        if(pilihan.equals("Data Barang")){

            model.addColumn("ID");
            model.addColumn("Kode");
            model.addColumn("Nama");
            model.addColumn("Kategori");
            model.addColumn("Stok");
            model.addColumn("Satuan");

            sql = "SELECT * FROM barang";

        }

        else if(pilihan.equals("Barang Masuk")){

            model.addColumn("ID");
            model.addColumn("ID Barang");
            model.addColumn("Tanggal");
            model.addColumn("Jumlah");

            sql = "SELECT * FROM barang_masuk";

        }

        else if(pilihan.equals("Barang Keluar")){

            model.addColumn("ID");
            model.addColumn("ID Barang");
            model.addColumn("Tanggal");
            model.addColumn("Jumlah");

            sql = "SELECT * FROM barang_keluar";

        }

        else if(pilihan.equals("Stock Opname")){

            model.addColumn("ID");
            model.addColumn("ID Barang");
            model.addColumn("Stok Sistem");
            model.addColumn("Stok Fisik");
            model.addColumn("Selisih");

            sql = "SELECT * FROM stock_opname";

        }

        PreparedStatement pst =
        conn.prepareStatement(sql);

        ResultSet rs =
        pst.executeQuery();

        while(rs.next()){

            if(pilihan.equals("Data Barang")){

                model.addRow(new Object[]{

                    rs.getString("id_barang"),
                    rs.getString("kode_barang"),
                    rs.getString("nama_barang"),
                    rs.getString("kategori"),
                    rs.getString("stok"),
                    rs.getString("satuan")

                });

            }

            else if(pilihan.equals("Barang Masuk")){

                model.addRow(new Object[]{

                    rs.getString("id_masuk"),
                    rs.getString("id_barang"),
                    rs.getString("tanggal"),
                    rs.getString("jumlah")

                });

            }

            else if(pilihan.equals("Barang Keluar")){

                model.addRow(new Object[]{

                    rs.getString("id_keluar"),
                    rs.getString("id_barang"),
                    rs.getString("tanggal"),
                    rs.getString("jumlah")

                });

            }

            else if(pilihan.equals("Stock Opname")){

                model.addRow(new Object[]{

                    rs.getString("id_opname"),
                    rs.getString("id_barang"),
                    rs.getString("stok_sistem"),
                    rs.getString("stok_fisik"),
                    rs.getString("selisih")

                });

            }

        }

        tblLaporan.setModel(model);

    }catch(Exception e){

        javax.swing.JOptionPane.showMessageDialog(
        this,
        e.getMessage());

    }
    }//GEN-LAST:event_btnTampilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTampil;
    private javax.swing.JComboBox cmbLaporan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLaporan;
    // End of variables declaration//GEN-END:variables
}
