/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package form;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import koneksi.koneksi;

/**
 *
 * @author Ahmad Noval
 */
public class StockOpnameForm extends javax.swing.JFrame {

    /**
     * Creates new form StockOpnameForm
     */
    public StockOpnameForm() {
        initComponents();
        setLocationRelativeTo(null);

    loadBarang();
    tampilOpname();
    }
private void loadBarang(){

    try{

        Connection conn =
        koneksi.getConnection();

        String sql =
        "SELECT kode_barang FROM barang";

        PreparedStatement pst =
        conn.prepareStatement(sql);

        ResultSet rs =
        pst.executeQuery();

        cmbBarang.removeAllItems();

        while(rs.next()){

            cmbBarang.addItem(
            rs.getString("kode_barang"));

        }

    }catch(Exception e){

        System.out.println(e);

    }

}
private void tampilOpname(){

    DefaultTableModel model =
    new DefaultTableModel();

    model.addColumn("ID");
    model.addColumn("Kode Barang");
    model.addColumn("Stok Sistem");
    model.addColumn("Stok Fisik");
    model.addColumn("Selisih");

    try{

        Connection conn =
        koneksi.getConnection();

        String sql =
        "SELECT so.id_opname, " +
        "b.kode_barang, " +
        "so.stok_sistem, " +
        "so.stok_fisik, " +
        "so.selisih " +
        "FROM stock_opname so " +
        "JOIN barang b " +
        "ON so.id_barang=b.id_barang";

        PreparedStatement pst =
        conn.prepareStatement(sql);

        ResultSet rs =
        pst.executeQuery();

        while(rs.next()){

            model.addRow(new Object[]{

                rs.getString("id_opname"),
                rs.getString("kode_barang"),
                rs.getString("stok_sistem"),
                rs.getString("stok_fisik"),
                rs.getString("selisih")

            });

        }

        tblOpname.setModel(model);

    }catch(Exception e){

        System.out.println(e);

    }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cmbBarang = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtStokSistem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtStokFisik = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSelisih = new javax.swing.JTextField();
        btnCek = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOpname = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Barang");

        cmbBarang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBarang.setSelectedIndex(-1);

        jLabel2.setText("Stok Sistem");

        jLabel3.setText("Stok Fisik");

        jLabel4.setText("Selisih");

        btnCek.setText("CEK");
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        tblOpname.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblOpname);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCek)
                        .addGap(29, 29, 29)
                        .addComponent(btnSimpan))
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtSelisih, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtStokFisik, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cmbBarang, javax.swing.GroupLayout.Alignment.LEADING, 0, 88, Short.MAX_VALUE)
                        .addComponent(txtStokSistem, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStokSistem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStokFisik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSelisih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCek)
                    .addComponent(btnSimpan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
        // TODO add your handling code here:
        try{

        Connection conn =
        koneksi.getConnection();

        String sql =
        "SELECT stok FROM barang " +
        "WHERE kode_barang=?";

        PreparedStatement pst =
        conn.prepareStatement(sql);

        pst.setString(
        1,
        cmbBarang.getSelectedItem().toString());

        ResultSet rs =
        pst.executeQuery();

        if(rs.next()){

            txtStokSistem.setText(
            rs.getString("stok"));

        }

    }catch(Exception e){

        JOptionPane.showMessageDialog(
        this,
        e.getMessage());

    }
    }//GEN-LAST:event_btnCekActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try{

        Connection conn =
        koneksi.getConnection();

        int stokSistem =
        Integer.parseInt(
        txtStokSistem.getText());

        int stokFisik =
        Integer.parseInt(
        txtStokFisik.getText());

        int selisih =
        stokFisik - stokSistem;

        txtSelisih.setText(
        String.valueOf(selisih));

        String sql =
        "INSERT INTO stock_opname" +
        "(id_barang,tanggal,stok_sistem,stok_fisik,selisih) " +
        "SELECT id_barang,CURDATE(),?,?,? " +
        "FROM barang WHERE kode_barang=?";

        PreparedStatement pst =
        conn.prepareStatement(sql);

        pst.setInt(1,stokSistem);
        pst.setInt(2,stokFisik);
        pst.setInt(3,selisih);

        pst.setString(
        4,
        cmbBarang.getSelectedItem().toString());

        pst.executeUpdate();

        // update stok sesuai fisik

        String sqlUpdate =
        "UPDATE barang " +
        "SET stok=? " +
        "WHERE kode_barang=?";

        PreparedStatement pstUpdate =
        conn.prepareStatement(sqlUpdate);

        pstUpdate.setInt(1,stokFisik);

        pstUpdate.setString(
        2,
        cmbBarang.getSelectedItem().toString());

        pstUpdate.executeUpdate();

        JOptionPane.showMessageDialog(
        this,
        "Stock Opname berhasil");

        tampilOpname();

    }catch(Exception e){

        JOptionPane.showMessageDialog(
        this,
        e.getMessage());

    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockOpnameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockOpnameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockOpnameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockOpnameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockOpnameForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCek;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox cmbBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblOpname;
    private javax.swing.JTextField txtSelisih;
    private javax.swing.JTextField txtStokFisik;
    private javax.swing.JTextField txtStokSistem;
    // End of variables declaration//GEN-END:variables
}
